services:
  bot:
    build:
      context: .
      dockerfile: services/bot/Dockerfile
    env_file:
      - ./services/bot/.env
    environment:
      - BRAIN_URL=brain:5050
      - VALKEY_URL=valkey://valkey:6379
    restart: unless-stopped
    networks:
      - internal

  brain:
    build:
      context: .
      dockerfile: services/brain/Dockerfile
    environment:
      - Valkey__Url=valkey:6379
    ports:
     - "8080:8080"
    restart: unless-stopped
    networks:
      - internal

  asr:
    build:
      context: .
      dockerfile: services/asr/Dockerfile
    environment:
      - ASR_MODEL=large-v3-turbo
      - ASR_DEVICE=cuda
      - ASR_COMPUTE_TYPE=float16
      - ASR_FLASH_ATTENTION=true
      - ASR_NUM_WORKERS=1
      - ASR_BEAM_SIZE=5
      - ASR_GRPC_PORT=6060
    restart: unless-stopped
    networks:
      - internal
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
      - asr_model_cache:/root/.cache/huggingface

  valkey:
    image: valkey/valkey:9-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - internal

networks:
  internal:

volumes:
  asr_model_cache:
